AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Template for an S3 Bucket

Parameters:
  BucketName:
    Description: Name for the S3 bucket
    Type: String
    MinLength: 3
    MaxLength: 63
    ConstraintDescription: The bucket name must be between 3 and 63 characters.

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      DeletionPolicy: "Delete"
